//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_booking_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reserva_habitacion_huesped
    {
        public int reserva_id { get; set; }
        public int habitacion_id { get; set; }
        public int huesped_id { get; set; }
        public Nullable<bool> asistencia_confirmada { get; set; }
        public string comentario_huesped { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
    
        public virtual tb_habitacion tb_habitacion { get; set; }
        public virtual tb_huesped tb_huesped { get; set; }
        public virtual tb_reserva tb_reserva { get; set; }
    }
}
