//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_booking_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_reserva_habitacion
    {
        public int Reserva_Id { get; set; }
        public int Habitacion_Id { get; set; }
        public string Habitacion_Nombre { get; set; }
        public Nullable<decimal> Precio_de_Estadia { get; set; }
        public System.DateTime Fecha_de_Entrada { get; set; }
        public System.DateTime Fecha_de_Salida { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Ultima_Modificacion { get; set; }
    }
}
