//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_booking_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_reserva_servicio
    {
        public int Reserva_Id { get; set; }
        public int Servicio_Id { get; set; }
        public string Servicio { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio_Total { get; set; }
        public System.DateTime Fecha_de_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_de_Ultima_Modificacion { get; set; }
    }
}
