//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyHotel_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hotel_databaseEntities : DbContext
    {
        public hotel_databaseEntities()
            : base("name=hotel_databaseEntities")
        {
            var ensureDLLIsCopied = System.Data.Entity.SqlServer.SqlProviderServices.Instance;

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_habitacion> tb_habitacion { get; set; }
        public virtual DbSet<tb_huesped> tb_huesped { get; set; }
        public virtual DbSet<tb_reserva> tb_reserva { get; set; }
        public virtual DbSet<tb_reserva_habitacion> tb_reserva_habitacion { get; set; }
        public virtual DbSet<tb_reserva_habitacion_huesped> tb_reserva_habitacion_huesped { get; set; }
        public virtual DbSet<tb_servicio> tb_servicio { get; set; }
        public virtual DbSet<tb_tipo_habitacion> tb_tipo_habitacion { get; set; }
        public virtual DbSet<tb_tipo_usuario> tb_tipo_usuario { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_reserva_servicio> tb_reserva_servicio { get; set; }
        public virtual DbSet<vw_habitacion> vw_habitacion { get; set; }
        public virtual DbSet<vw_huesped> vw_huesped { get; set; }
        public virtual DbSet<vw_reserva> vw_reserva { get; set; }
        public virtual DbSet<vw_reserva_habitacion> vw_reserva_habitacion { get; set; }
        public virtual DbSet<vw_reserva_habitacion_huesped> vw_reserva_habitacion_huesped { get; set; }
        public virtual DbSet<vw_reserva_servicio> vw_reserva_servicio { get; set; }
        public virtual DbSet<vw_servicio> vw_servicio { get; set; }
        public virtual DbSet<vw_tipo_habitacion> vw_tipo_habitacion { get; set; }
        public virtual DbSet<vw_tipo_usuario> vw_tipo_usuario { get; set; }
        public virtual DbSet<vw_usuario> vw_usuario { get; set; }
    
        public virtual int usp_actualizar_estado_usuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_estado_usuario", idParameter);
        }
    
        public virtual int usp_actualizar_tb_habitacion(Nullable<int> habitacion_id, string habitacion_nombre, Nullable<byte> habitacion_aforo, Nullable<int> usuario_ult_modificacion, Nullable<int> tipo_habitacion_id, Nullable<bool> estado_habitacion)
        {
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var habitacion_nombreParameter = habitacion_nombre != null ?
                new ObjectParameter("habitacion_nombre", habitacion_nombre) :
                new ObjectParameter("habitacion_nombre", typeof(string));
    
            var habitacion_aforoParameter = habitacion_aforo.HasValue ?
                new ObjectParameter("habitacion_aforo", habitacion_aforo) :
                new ObjectParameter("habitacion_aforo", typeof(byte));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion.HasValue ?
                new ObjectParameter("usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("usuario_ult_modificacion", typeof(int));
    
            var tipo_habitacion_idParameter = tipo_habitacion_id.HasValue ?
                new ObjectParameter("tipo_habitacion_id", tipo_habitacion_id) :
                new ObjectParameter("tipo_habitacion_id", typeof(int));
    
            var estado_habitacionParameter = estado_habitacion.HasValue ?
                new ObjectParameter("estado_habitacion", estado_habitacion) :
                new ObjectParameter("estado_habitacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_habitacion", habitacion_idParameter, habitacion_nombreParameter, habitacion_aforoParameter, usuario_ult_modificacionParameter, tipo_habitacion_idParameter, estado_habitacionParameter);
        }
    
        public virtual int usp_actualizar_tb_huesped(Nullable<int> huesped_id, string huesped_nombre, string huesped_telefono, string huesped_dni, Nullable<System.DateTime> fecha_ult_modificacion)
        {
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            var huesped_nombreParameter = huesped_nombre != null ?
                new ObjectParameter("huesped_nombre", huesped_nombre) :
                new ObjectParameter("huesped_nombre", typeof(string));
    
            var huesped_telefonoParameter = huesped_telefono != null ?
                new ObjectParameter("huesped_telefono", huesped_telefono) :
                new ObjectParameter("huesped_telefono", typeof(string));
    
            var huesped_dniParameter = huesped_dni != null ?
                new ObjectParameter("huesped_dni", huesped_dni) :
                new ObjectParameter("huesped_dni", typeof(string));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("fecha_ult_modificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_huesped", huesped_idParameter, huesped_nombreParameter, huesped_telefonoParameter, huesped_dniParameter, fecha_ult_modificacionParameter);
        }
    
        public virtual int usp_actualizar_tb_reserva(Nullable<int> reserva_id, Nullable<int> usuario_id, Nullable<int> usuario_ult_modificacion, string usuario_dni, string reserva_nombre, string usuario_telefono, Nullable<bool> reserva_estado, Nullable<bool> estado_pago)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion.HasValue ?
                new ObjectParameter("usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("usuario_ult_modificacion", typeof(int));
    
            var usuario_dniParameter = usuario_dni != null ?
                new ObjectParameter("usuario_dni", usuario_dni) :
                new ObjectParameter("usuario_dni", typeof(string));
    
            var reserva_nombreParameter = reserva_nombre != null ?
                new ObjectParameter("reserva_nombre", reserva_nombre) :
                new ObjectParameter("reserva_nombre", typeof(string));
    
            var usuario_telefonoParameter = usuario_telefono != null ?
                new ObjectParameter("usuario_telefono", usuario_telefono) :
                new ObjectParameter("usuario_telefono", typeof(string));
    
            var reserva_estadoParameter = reserva_estado.HasValue ?
                new ObjectParameter("reserva_estado", reserva_estado) :
                new ObjectParameter("reserva_estado", typeof(bool));
    
            var estado_pagoParameter = estado_pago.HasValue ?
                new ObjectParameter("estado_pago", estado_pago) :
                new ObjectParameter("estado_pago", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_reserva", reserva_idParameter, usuario_idParameter, usuario_ult_modificacionParameter, usuario_dniParameter, reserva_nombreParameter, usuario_telefonoParameter, reserva_estadoParameter, estado_pagoParameter);
        }
    
        public virtual int usp_actualizar_tb_reserva_habitacion(Nullable<int> reserva_id, Nullable<int> habitacion_id, Nullable<System.DateTime> fecha_checkin, Nullable<System.DateTime> fecha_checkout)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var fecha_checkinParameter = fecha_checkin.HasValue ?
                new ObjectParameter("fecha_checkin", fecha_checkin) :
                new ObjectParameter("fecha_checkin", typeof(System.DateTime));
    
            var fecha_checkoutParameter = fecha_checkout.HasValue ?
                new ObjectParameter("fecha_checkout", fecha_checkout) :
                new ObjectParameter("fecha_checkout", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_reserva_habitacion", reserva_idParameter, habitacion_idParameter, fecha_checkinParameter, fecha_checkoutParameter);
        }
    
        public virtual int usp_actualizar_tb_reserva_habitacion_huesped(Nullable<int> reserva_id, Nullable<int> habitacion_id, Nullable<int> huesped_id, Nullable<bool> asistencia_confirmada, string comentario_huesped)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            var asistencia_confirmadaParameter = asistencia_confirmada.HasValue ?
                new ObjectParameter("asistencia_confirmada", asistencia_confirmada) :
                new ObjectParameter("asistencia_confirmada", typeof(bool));
    
            var comentario_huespedParameter = comentario_huesped != null ?
                new ObjectParameter("comentario_huesped", comentario_huesped) :
                new ObjectParameter("comentario_huesped", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_reserva_habitacion_huesped", reserva_idParameter, habitacion_idParameter, huesped_idParameter, asistencia_confirmadaParameter, comentario_huespedParameter);
        }
    
        public virtual int usp_actualizar_tb_reserva_servicio(Nullable<int> reserva_id, Nullable<int> servicio_id, Nullable<int> cantidad)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_reserva_servicio", reserva_idParameter, servicio_idParameter, cantidadParameter);
        }
    
        public virtual int usp_actualizar_tb_servicio(Nullable<int> servicio_id, string servicio_descripcion, Nullable<decimal> servicio_precio, Nullable<bool> servicio_estado)
        {
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            var servicio_descripcionParameter = servicio_descripcion != null ?
                new ObjectParameter("servicio_descripcion", servicio_descripcion) :
                new ObjectParameter("servicio_descripcion", typeof(string));
    
            var servicio_precioParameter = servicio_precio.HasValue ?
                new ObjectParameter("servicio_precio", servicio_precio) :
                new ObjectParameter("servicio_precio", typeof(decimal));
    
            var servicio_estadoParameter = servicio_estado.HasValue ?
                new ObjectParameter("servicio_estado", servicio_estado) :
                new ObjectParameter("servicio_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_servicio", servicio_idParameter, servicio_descripcionParameter, servicio_precioParameter, servicio_estadoParameter);
        }
    
        public virtual int usp_actualizar_tb_tipo_habitacion(Nullable<int> tipo_habitacion_id, string tipo_habitacion_descripcion, Nullable<decimal> costo_noche)
        {
            var tipo_habitacion_idParameter = tipo_habitacion_id.HasValue ?
                new ObjectParameter("tipo_habitacion_id", tipo_habitacion_id) :
                new ObjectParameter("tipo_habitacion_id", typeof(int));
    
            var tipo_habitacion_descripcionParameter = tipo_habitacion_descripcion != null ?
                new ObjectParameter("tipo_habitacion_descripcion", tipo_habitacion_descripcion) :
                new ObjectParameter("tipo_habitacion_descripcion", typeof(string));
    
            var costo_nocheParameter = costo_noche.HasValue ?
                new ObjectParameter("costo_noche", costo_noche) :
                new ObjectParameter("costo_noche", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_tipo_habitacion", tipo_habitacion_idParameter, tipo_habitacion_descripcionParameter, costo_nocheParameter);
        }
    
        public virtual int usp_actualizar_tb_tipo_usuario(Nullable<int> tipo_usuario_id, string tipo_usuario_descripcion)
        {
            var tipo_usuario_idParameter = tipo_usuario_id.HasValue ?
                new ObjectParameter("tipo_usuario_id", tipo_usuario_id) :
                new ObjectParameter("tipo_usuario_id", typeof(int));
    
            var tipo_usuario_descripcionParameter = tipo_usuario_descripcion != null ?
                new ObjectParameter("tipo_usuario_descripcion", tipo_usuario_descripcion) :
                new ObjectParameter("tipo_usuario_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_tipo_usuario", tipo_usuario_idParameter, tipo_usuario_descripcionParameter);
        }
    
        public virtual int usp_actualizar_tb_usuario(Nullable<int> usuario_id, string usuario_nombre, string usuario_correo, string usuario_password, Nullable<int> tipo_usuario_id, Nullable<bool> estado_usuario)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            var usuario_nombreParameter = usuario_nombre != null ?
                new ObjectParameter("usuario_nombre", usuario_nombre) :
                new ObjectParameter("usuario_nombre", typeof(string));
    
            var usuario_correoParameter = usuario_correo != null ?
                new ObjectParameter("usuario_correo", usuario_correo) :
                new ObjectParameter("usuario_correo", typeof(string));
    
            var usuario_passwordParameter = usuario_password != null ?
                new ObjectParameter("usuario_password", usuario_password) :
                new ObjectParameter("usuario_password", typeof(string));
    
            var tipo_usuario_idParameter = tipo_usuario_id.HasValue ?
                new ObjectParameter("tipo_usuario_id", tipo_usuario_id) :
                new ObjectParameter("tipo_usuario_id", typeof(int));
    
            var estado_usuarioParameter = estado_usuario.HasValue ?
                new ObjectParameter("estado_usuario", estado_usuario) :
                new ObjectParameter("estado_usuario", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_tb_usuario", usuario_idParameter, usuario_nombreParameter, usuario_correoParameter, usuario_passwordParameter, tipo_usuario_idParameter, estado_usuarioParameter);
        }
    
        public virtual int usp_borrar_tb_habitacion(Nullable<int> habitacion_id)
        {
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_habitacion", habitacion_idParameter);
        }
    
        public virtual int usp_borrar_tb_huesped(Nullable<int> huesped_id)
        {
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_huesped", huesped_idParameter);
        }
    
        public virtual int usp_borrar_tb_reserva(Nullable<int> reserva_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_reserva", reserva_idParameter);
        }
    
        public virtual int usp_borrar_tb_reserva_habitacion(Nullable<int> reserva_id, Nullable<int> habitacion_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_reserva_habitacion", reserva_idParameter, habitacion_idParameter);
        }
    
        public virtual int usp_borrar_tb_reserva_habitacion_huesped(Nullable<int> reserva_id, Nullable<int> habitacion_id, Nullable<int> huesped_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_reserva_habitacion_huesped", reserva_idParameter, habitacion_idParameter, huesped_idParameter);
        }
    
        public virtual int usp_borrar_tb_reserva_servicio(Nullable<int> reserva_id, Nullable<int> servicio_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_reserva_servicio", reserva_idParameter, servicio_idParameter);
        }
    
        public virtual int usp_borrar_tb_servicio(Nullable<int> servicio_id)
        {
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_servicio", servicio_idParameter);
        }
    
        public virtual int usp_borrar_tb_tipo_habitacion(Nullable<int> tipo_habitacion_id)
        {
            var tipo_habitacion_idParameter = tipo_habitacion_id.HasValue ?
                new ObjectParameter("tipo_habitacion_id", tipo_habitacion_id) :
                new ObjectParameter("tipo_habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_tipo_habitacion", tipo_habitacion_idParameter);
        }
    
        public virtual int usp_borrar_tb_tipo_usuario(Nullable<int> tipo_usuario_id)
        {
            var tipo_usuario_idParameter = tipo_usuario_id.HasValue ?
                new ObjectParameter("tipo_usuario_id", tipo_usuario_id) :
                new ObjectParameter("tipo_usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_tipo_usuario", tipo_usuario_idParameter);
        }
    
        public virtual int usp_borrar_tb_usuario(Nullable<int> usuario_id)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_tb_usuario", usuario_idParameter);
        }
    
        public virtual int usp_crear_tb_habitacion(Nullable<int> tipo_habitacion_id, string habitacion_nombre, Nullable<short> habitacion_aforo, Nullable<bool> estado_habitacion)
        {
            var tipo_habitacion_idParameter = tipo_habitacion_id.HasValue ?
                new ObjectParameter("tipo_habitacion_id", tipo_habitacion_id) :
                new ObjectParameter("tipo_habitacion_id", typeof(int));
    
            var habitacion_nombreParameter = habitacion_nombre != null ?
                new ObjectParameter("habitacion_nombre", habitacion_nombre) :
                new ObjectParameter("habitacion_nombre", typeof(string));
    
            var habitacion_aforoParameter = habitacion_aforo.HasValue ?
                new ObjectParameter("habitacion_aforo", habitacion_aforo) :
                new ObjectParameter("habitacion_aforo", typeof(short));
    
            var estado_habitacionParameter = estado_habitacion.HasValue ?
                new ObjectParameter("estado_habitacion", estado_habitacion) :
                new ObjectParameter("estado_habitacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_habitacion", tipo_habitacion_idParameter, habitacion_nombreParameter, habitacion_aforoParameter, estado_habitacionParameter);
        }
    
        public virtual int usp_crear_tb_huesped(string huesped_nombre, string huesped_telefono, string huesped_dni)
        {
            var huesped_nombreParameter = huesped_nombre != null ?
                new ObjectParameter("huesped_nombre", huesped_nombre) :
                new ObjectParameter("huesped_nombre", typeof(string));
    
            var huesped_telefonoParameter = huesped_telefono != null ?
                new ObjectParameter("huesped_telefono", huesped_telefono) :
                new ObjectParameter("huesped_telefono", typeof(string));
    
            var huesped_dniParameter = huesped_dni != null ?
                new ObjectParameter("huesped_dni", huesped_dni) :
                new ObjectParameter("huesped_dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_huesped", huesped_nombreParameter, huesped_telefonoParameter, huesped_dniParameter);
        }
    
        public virtual ObjectResult<usp_crear_tb_reserva_Result> usp_crear_tb_reserva(Nullable<int> usuario_id, string usuario_dni, string usuario_telefono, string reserva_nombre)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            var usuario_dniParameter = usuario_dni != null ?
                new ObjectParameter("usuario_dni", usuario_dni) :
                new ObjectParameter("usuario_dni", typeof(string));
    
            var usuario_telefonoParameter = usuario_telefono != null ?
                new ObjectParameter("usuario_telefono", usuario_telefono) :
                new ObjectParameter("usuario_telefono", typeof(string));
    
            var reserva_nombreParameter = reserva_nombre != null ?
                new ObjectParameter("reserva_nombre", reserva_nombre) :
                new ObjectParameter("reserva_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_crear_tb_reserva_Result>("usp_crear_tb_reserva", usuario_idParameter, usuario_dniParameter, usuario_telefonoParameter, reserva_nombreParameter);
        }
    
        public virtual int usp_crear_tb_reserva_habitacion(Nullable<int> reserva_id, Nullable<int> habitacion_id, Nullable<System.DateTime> fecha_checkin, Nullable<System.DateTime> fecha_checkout)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var fecha_checkinParameter = fecha_checkin.HasValue ?
                new ObjectParameter("fecha_checkin", fecha_checkin) :
                new ObjectParameter("fecha_checkin", typeof(System.DateTime));
    
            var fecha_checkoutParameter = fecha_checkout.HasValue ?
                new ObjectParameter("fecha_checkout", fecha_checkout) :
                new ObjectParameter("fecha_checkout", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_reserva_habitacion", reserva_idParameter, habitacion_idParameter, fecha_checkinParameter, fecha_checkoutParameter);
        }
    
        public virtual int usp_crear_tb_reserva_habitacion_huesped(Nullable<int> reserva_id, Nullable<int> habitacion_id, Nullable<int> huesped_id, Nullable<bool> asistencia_confirmada, string comentario_huesped)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            var asistencia_confirmadaParameter = asistencia_confirmada.HasValue ?
                new ObjectParameter("asistencia_confirmada", asistencia_confirmada) :
                new ObjectParameter("asistencia_confirmada", typeof(bool));
    
            var comentario_huespedParameter = comentario_huesped != null ?
                new ObjectParameter("comentario_huesped", comentario_huesped) :
                new ObjectParameter("comentario_huesped", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_reserva_habitacion_huesped", reserva_idParameter, habitacion_idParameter, huesped_idParameter, asistencia_confirmadaParameter, comentario_huespedParameter);
        }
    
        public virtual int usp_crear_tb_reserva_servicio(Nullable<int> reserva_id, Nullable<int> servicio_id, Nullable<int> cantidad)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_reserva_servicio", reserva_idParameter, servicio_idParameter, cantidadParameter);
        }
    
        public virtual int usp_crear_tb_servicio(string servicio_descripcion, Nullable<decimal> servicio_precio, Nullable<bool> servicio_estado)
        {
            var servicio_descripcionParameter = servicio_descripcion != null ?
                new ObjectParameter("servicio_descripcion", servicio_descripcion) :
                new ObjectParameter("servicio_descripcion", typeof(string));
    
            var servicio_precioParameter = servicio_precio.HasValue ?
                new ObjectParameter("servicio_precio", servicio_precio) :
                new ObjectParameter("servicio_precio", typeof(decimal));
    
            var servicio_estadoParameter = servicio_estado.HasValue ?
                new ObjectParameter("servicio_estado", servicio_estado) :
                new ObjectParameter("servicio_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_servicio", servicio_descripcionParameter, servicio_precioParameter, servicio_estadoParameter);
        }
    
        public virtual int usp_crear_tb_tipo_habitacion(string tipo_habitacion_descripcion, Nullable<decimal> costo_noche)
        {
            var tipo_habitacion_descripcionParameter = tipo_habitacion_descripcion != null ?
                new ObjectParameter("tipo_habitacion_descripcion", tipo_habitacion_descripcion) :
                new ObjectParameter("tipo_habitacion_descripcion", typeof(string));
    
            var costo_nocheParameter = costo_noche.HasValue ?
                new ObjectParameter("costo_noche", costo_noche) :
                new ObjectParameter("costo_noche", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_tipo_habitacion", tipo_habitacion_descripcionParameter, costo_nocheParameter);
        }
    
        public virtual int usp_crear_tb_tipo_usuario(string tipo_usuario_descripcion)
        {
            var tipo_usuario_descripcionParameter = tipo_usuario_descripcion != null ?
                new ObjectParameter("tipo_usuario_descripcion", tipo_usuario_descripcion) :
                new ObjectParameter("tipo_usuario_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_tipo_usuario", tipo_usuario_descripcionParameter);
        }
    
        public virtual int usp_crear_tb_usuario(Nullable<int> tipo_usuario_id, string usuario_nombre, string usuario_correo, string usuario_password, Nullable<bool> usuario_estado)
        {
            var tipo_usuario_idParameter = tipo_usuario_id.HasValue ?
                new ObjectParameter("tipo_usuario_id", tipo_usuario_id) :
                new ObjectParameter("tipo_usuario_id", typeof(int));
    
            var usuario_nombreParameter = usuario_nombre != null ?
                new ObjectParameter("usuario_nombre", usuario_nombre) :
                new ObjectParameter("usuario_nombre", typeof(string));
    
            var usuario_correoParameter = usuario_correo != null ?
                new ObjectParameter("usuario_correo", usuario_correo) :
                new ObjectParameter("usuario_correo", typeof(string));
    
            var usuario_passwordParameter = usuario_password != null ?
                new ObjectParameter("usuario_password", usuario_password) :
                new ObjectParameter("usuario_password", typeof(string));
    
            var usuario_estadoParameter = usuario_estado.HasValue ?
                new ObjectParameter("usuario_estado", usuario_estado) :
                new ObjectParameter("usuario_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_crear_tb_usuario", tipo_usuario_idParameter, usuario_nombreParameter, usuario_correoParameter, usuario_passwordParameter, usuario_estadoParameter);
        }
    
        public virtual int usp_eliminar_tb_reserva_servicio(Nullable<int> reserva_id, Nullable<int> servicio_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_tb_reserva_servicio", reserva_idParameter, servicio_idParameter);
        }
    
        public virtual ObjectResult<usp_ingreso_tb_usuario_Result> usp_ingreso_tb_usuario(string usuario_nombre, string usuario_password)
        {
            var usuario_nombreParameter = usuario_nombre != null ?
                new ObjectParameter("usuario_nombre", usuario_nombre) :
                new ObjectParameter("usuario_nombre", typeof(string));
    
            var usuario_passwordParameter = usuario_password != null ?
                new ObjectParameter("usuario_password", usuario_password) :
                new ObjectParameter("usuario_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ingreso_tb_usuario_Result>("usp_ingreso_tb_usuario", usuario_nombreParameter, usuario_passwordParameter);
        }
    
        public virtual ObjectResult<usp_listar_tb_habitacion_Result> usp_listar_tb_habitacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_habitacion_Result>("usp_listar_tb_habitacion");
        }
    
        public virtual ObjectResult<usp_listar_tb_huesped_Result> usp_listar_tb_huesped()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_huesped_Result>("usp_listar_tb_huesped");
        }
    
        public virtual ObjectResult<usp_listar_tb_reserva_Result> usp_listar_tb_reserva()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_reserva_Result>("usp_listar_tb_reserva");
        }
    
        public virtual ObjectResult<usp_listar_tb_reserva_habitacion_Result> usp_listar_tb_reserva_habitacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_reserva_habitacion_Result>("usp_listar_tb_reserva_habitacion");
        }
    
        public virtual ObjectResult<usp_listar_tb_reserva_habitacion_huesped_Result> usp_listar_tb_reserva_habitacion_huesped()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_reserva_habitacion_huesped_Result>("usp_listar_tb_reserva_habitacion_huesped");
        }
    
        public virtual ObjectResult<usp_listar_tb_reserva_servicio_Result> usp_listar_tb_reserva_servicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_reserva_servicio_Result>("usp_listar_tb_reserva_servicio");
        }
    
        public virtual ObjectResult<usp_listar_tb_servicio_Result> usp_listar_tb_servicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_servicio_Result>("usp_listar_tb_servicio");
        }
    
        public virtual ObjectResult<usp_listar_tb_tipo_habitacion_Result> usp_listar_tb_tipo_habitacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_tipo_habitacion_Result>("usp_listar_tb_tipo_habitacion");
        }
    
        public virtual ObjectResult<usp_listar_tb_tipo_usuario_Result> usp_listar_tb_tipo_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_tipo_usuario_Result>("usp_listar_tb_tipo_usuario");
        }
    
        public virtual ObjectResult<usp_listar_tb_usuario_Result> usp_listar_tb_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tb_usuario_Result>("usp_listar_tb_usuario");
        }
    
        public virtual ObjectResult<usp_obtener_tb_habitacion_id_Result> usp_obtener_tb_habitacion_id(Nullable<int> habitacion_id)
        {
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_habitacion_id_Result>("usp_obtener_tb_habitacion_id", habitacion_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_habitacion_tipo_id_Result> usp_obtener_tb_habitacion_tipo_id(Nullable<int> tipo_habitacion_id)
        {
            var tipo_habitacion_idParameter = tipo_habitacion_id.HasValue ?
                new ObjectParameter("tipo_habitacion_id", tipo_habitacion_id) :
                new ObjectParameter("tipo_habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_habitacion_tipo_id_Result>("usp_obtener_tb_habitacion_tipo_id", tipo_habitacion_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_huesped_id_Result> usp_obtener_tb_huesped_id(Nullable<int> huesped_id)
        {
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_huesped_id_Result>("usp_obtener_tb_huesped_id", huesped_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_habitacion_huesped_Result> usp_obtener_tb_reserva_habitacion_huesped(string huesped_nombre)
        {
            var huesped_nombreParameter = huesped_nombre != null ?
                new ObjectParameter("huesped_nombre", huesped_nombre) :
                new ObjectParameter("huesped_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_habitacion_huesped_Result>("usp_obtener_tb_reserva_habitacion_huesped", huesped_nombreParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_habitacion_huesped_id_Result> usp_obtener_tb_reserva_habitacion_huesped_id(Nullable<int> reserva_id, Nullable<int> habitacion_id, Nullable<int> huesped_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            var huesped_idParameter = huesped_id.HasValue ?
                new ObjectParameter("huesped_id", huesped_id) :
                new ObjectParameter("huesped_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_habitacion_huesped_id_Result>("usp_obtener_tb_reserva_habitacion_huesped_id", reserva_idParameter, habitacion_idParameter, huesped_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_habitacion_huesped_todo_Result> usp_obtener_tb_reserva_habitacion_huesped_todo(Nullable<int> reserva_id, Nullable<int> habitacion_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_habitacion_huesped_todo_Result>("usp_obtener_tb_reserva_habitacion_huesped_todo", reserva_idParameter, habitacion_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_habitacion_id_Result> usp_obtener_tb_reserva_habitacion_id(Nullable<int> reserva_id, Nullable<int> habitacion_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var habitacion_idParameter = habitacion_id.HasValue ?
                new ObjectParameter("habitacion_id", habitacion_id) :
                new ObjectParameter("habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_habitacion_id_Result>("usp_obtener_tb_reserva_habitacion_id", reserva_idParameter, habitacion_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_habitacion_reserva_Result> usp_obtener_tb_reserva_habitacion_reserva(Nullable<int> reserva_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_habitacion_reserva_Result>("usp_obtener_tb_reserva_habitacion_reserva", reserva_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_id_Result> usp_obtener_tb_reserva_id(Nullable<int> reserva_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_id_Result>("usp_obtener_tb_reserva_id", reserva_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_servicio_id_Result> usp_obtener_tb_reserva_servicio_id(Nullable<int> reserva_id, Nullable<int> servicio_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_servicio_id_Result>("usp_obtener_tb_reserva_servicio_id", reserva_idParameter, servicio_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_reserva_servicio_reserva_Result> usp_obtener_tb_reserva_servicio_reserva(Nullable<int> reserva_id)
        {
            var reserva_idParameter = reserva_id.HasValue ?
                new ObjectParameter("reserva_id", reserva_id) :
                new ObjectParameter("reserva_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_reserva_servicio_reserva_Result>("usp_obtener_tb_reserva_servicio_reserva", reserva_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_servicio_id_Result> usp_obtener_tb_servicio_id(Nullable<int> servicio_id)
        {
            var servicio_idParameter = servicio_id.HasValue ?
                new ObjectParameter("servicio_id", servicio_id) :
                new ObjectParameter("servicio_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_servicio_id_Result>("usp_obtener_tb_servicio_id", servicio_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_tipo_habitacion_id_Result> usp_obtener_tb_tipo_habitacion_id(Nullable<int> tipo_habitacion_id)
        {
            var tipo_habitacion_idParameter = tipo_habitacion_id.HasValue ?
                new ObjectParameter("tipo_habitacion_id", tipo_habitacion_id) :
                new ObjectParameter("tipo_habitacion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_tipo_habitacion_id_Result>("usp_obtener_tb_tipo_habitacion_id", tipo_habitacion_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_tipo_usuario_id_Result> usp_obtener_tb_tipo_usuario_id(Nullable<int> tipo_usuario_id)
        {
            var tipo_usuario_idParameter = tipo_usuario_id.HasValue ?
                new ObjectParameter("tipo_usuario_id", tipo_usuario_id) :
                new ObjectParameter("tipo_usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_tipo_usuario_id_Result>("usp_obtener_tb_tipo_usuario_id", tipo_usuario_idParameter);
        }
    
        public virtual ObjectResult<usp_obtener_tb_usuario_id_Result> usp_obtener_tb_usuario_id(Nullable<int> usuario_id)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_tb_usuario_id_Result>("usp_obtener_tb_usuario_id", usuario_idParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerEstadisticasPorMesHuesped_Result> sp_ObtenerEstadisticasPorMesHuesped()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerEstadisticasPorMesHuesped_Result>("sp_ObtenerEstadisticasPorMesHuesped");
        }
    
        public virtual ObjectResult<sp_graficoReservas_Result> sp_graficoReservas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_graficoReservas_Result>("sp_graficoReservas");
        }
    }
}
