//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyHotel_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_huesped
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_huesped()
        {
            this.tb_reserva_habitacion_huesped = new HashSet<tb_reserva_habitacion_huesped>();
        }
    
        public int huesped_id { get; set; }
        public string huesped_nombre { get; set; }
        public string huesped_telefono { get; set; }
        public string huesped_dni { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
        public string huesped_correo { get; set; }
        public string huesped_sexo { get; set; }
        public Nullable<int> usuario_ult_modificacion { get; set; }
        public Nullable<bool> huesped_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserva_habitacion_huesped> tb_reserva_habitacion_huesped { get; set; }
    }
}
