//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyHotel_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_habitacion()
        {
            this.tb_reserva_habitacion_huesped = new HashSet<tb_reserva_habitacion_huesped>();
            this.tb_reserva_habitacion = new HashSet<tb_reserva_habitacion>();
        }
    
        public int habitacion_id { get; set; }
        public int tipo_habitacion_id { get; set; }
        public Nullable<byte> habitacion_aforo { get; set; }
        public bool estado_habitacion { get; set; }
        public string habitacion_nombre { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
        public Nullable<int> usuario_ult_modificacion { get; set; }
    
        public virtual tb_tipo_habitacion tb_tipo_habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserva_habitacion_huesped> tb_reserva_habitacion_huesped { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserva_habitacion> tb_reserva_habitacion { get; set; }
    }
}
