//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyHotel_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reserva_habitacion
    {
        public int reserva_id { get; set; }
        public int habitacion_id { get; set; }
        public Nullable<decimal> precio_estadia { get; set; }
        public System.DateTime fecha_checkin { get; set; }
        public System.DateTime fecha_checkout { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
    
        public virtual tb_habitacion tb_habitacion { get; set; }
        public virtual tb_reserva tb_reserva { get; set; }
    }
}
