//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyHotel_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tipo_habitacion()
        {
            this.tb_habitacion = new HashSet<tb_habitacion>();
        }
    
        public int tipo_habitacion_id { get; set; }
        public string tipo_habitacion_descripcion { get; set; }
        public decimal costo_noche { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_habitacion> tb_habitacion { get; set; }
    }
}
